<?php
/**
* @file
* Módulo Users Login Forcontu
* Este módulo nos permitirá guardar un registro de todos los accesos y cierres de sesión del sitio
*/

/**
 * Implements hook_user_login().
 */
function users_login_forcontu_user_login(&$edit, $account) {
  // Cuando un usuario se loguea se añade un registro a la tabla users_login_forcontu.
  db_insert('users_login_forcontu')
    ->fields(array(
      'uid' => $account->uid,//identificador del usuario
      'login_date' => time(),//fecha timestamp
      'login_type' => 'login',//tipo de acceso login
      'ip' => ip_address(),//dirección ip desde donde accede el usuario
    ))
    ->execute();
}

/**
 * Implements hook_user_logout().
 */
function users_login_forcontu_user_logout($account) {
  // Cuando un usuario se desloguea se añade un registro a la tabla users_login_forcontu.
  db_insert('users_login_forcontu')
    ->fields(array(
      'uid' => $account->uid,//identificador del usuario
      'login_date' => time(),//fecha timestamp
      'login_type' => 'logout',//tipo de acceso login
      'ip' => ip_address(),//dirección ip desde donde accede el usuario
    ))
    ->execute();
}

/**
 * Implements hook_user_load().
 */
function users_login_forcontu_user_load($users) {
  //Calculamos login de usuarios
  $result_in = db_query("SELECT uid , COUNT(uid) AS login_count FROM {users_login_forcontu} WHERE  login_type='login' GROUP BY uid", array(':uids' => array_keys($users)));
  foreach ($result_in as $record) {
    $users[$record->uid]->login_count = $record->login_count;
  }
  //Calculamos logout de usuarios
  $result_out = db_query("SELECT uid , COUNT(uid) AS logout_count FROM {users_login_forcontu} WHERE  login_type='logout' GROUP BY uid", array(':uids' => array_keys($users)));
  foreach ($result_out as $record) {
    $users[$record->uid]->logout_count = $record->logout_count;
  }

  //dpm($users);
}

/**
 * Implements hook_user_categories().
 */
function users_login_forcontu_user_categories() {
  return array(array(
    'name' => 'login_count',
    'title' => t('Login counter'),
    'access callback' => 'user_access',
    'weight' => 5,
  ));
}

/**
 * Implements hook_user_view().
 */
function users_login_forcontu_user_view($account, $view_mode, $langcode) {
  //dpm($account);
  $account->content['login_count'] = array();
  $account->content['login_count'] = array(
    '#type' => 'user_profile_category',
    '#attributes' => array('class' => 'contador-accesos-usuario'),
    '#weight' => 5,
    '#title' => t('Login count'),
  );
  $account->content['login_count']['login'] = array(
    '#type' => 'user_profile_item',
    '#markup' => 'Logins: ' . $account->login_count,
    '#attributes' => array('class' => 'login-count'),
    '#weight' => 1,
  );
  $account->content['login_count']['logout'] = array(
    '#type' => 'user_profile_item',
    '#markup' => 'Logouts: ' . $account->logout_count,
    '#attributes' => array('class' => 'login-count'),
    '#weight' => 2,
  );
}